// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuyoxclnyikqrrmvpzux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1eW94Y2xueWlrcXJybXZwenV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjU2ODcsImV4cCI6MjA2MjA0MTY4N30.vdjIjUBR_p1BM2uQb1LALY-9h4FQPmEYYpxtAd12jrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);